# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build NDepend Analysis for GitHub Pages

env:
  PROJECT_PATH_CORE: build/Stride.sln

on:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: windows-2022

    steps:
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2          

      - name: Checkout Stride (note the LFS)
        uses: actions/checkout@v4
        with:
          repository: stride3d/stride
          token: ${{ secrets.GITHUB_TOKEN }}
      #   path: stride
          lfs: true

      #- name: Restore Stride dependencies
      #  run: dotnet restore ${{ env.PROJECT_PATH_CORE }}

      - name: Build Stride.sln
        run: msbuild build/Stride.build -t:Build
      #  run: dotnet build ${{ env.PROJECT_PATH_CORE }} --no-restore

      - name: NDepend
        uses: ndepend/ndepend-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          license: ${{ secrets.NDependLicense }}
          solution: build/Stride.sln      

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3.9.2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: stride-docs/_site
      #     publish_branch: gh-pages
